import { useState, useCallback, useRef, useEffect, useMemo } from "react";

// ─── Constants ─────────────────────────────────────────────────────────────────

const NODE_DEFS = {
  fileInput:   { color: "#3b82f6", icon: "📄" },
  processor:   { color: "#8b5cf6", icon: "⚙️" },
  embeddings:  { color: "#f59e0b", icon: "🧬" },
  vectorStore: { color: "#10b981", icon: "🗄️" },
  retriever:   { color: "#f97316", icon: "🎯" },
  llm:         { color: "#ec4899", icon: "🧠" },
  chatUI:      { color: "#6366f1", icon: "💬" },
  output:      { color: "#14b8a6", icon: "✨" },
  webScraper:  { color: "#a855f7", icon: "🕷️" },
  apiInput:    { color: "#06b6d4", icon: "🔌" },
};

const DEFAULT_WORKFLOW = {
  name: "PDF Q&A Chatbot",
  nodes: [
    { id:"1", type:"fileInput",   pos:{x:60,  y:120}, label:"PDF Upload",    desc:"Accept PDF uploads",              color:"#3b82f6", icon:"📄", params:{accept:".pdf", multiple:"false"} },
    { id:"2", type:"processor",   pos:{x:300, y:120}, label:"PDF Extractor", desc:"Extract text from pages",         color:"#8b5cf6", icon:"⚙️", params:{engine:"pdf-parse"} },
    { id:"3", type:"processor",   pos:{x:540, y:120}, label:"Text Splitter", desc:"Chunk into overlapping segments", color:"#8b5cf6", icon:"✂️", params:{chunkSize:"1000", overlap:"200"} },
    { id:"4", type:"embeddings",  pos:{x:780, y:120}, label:"Embeddings",    desc:"OpenAI text-embedding-3-small",   color:"#f59e0b", icon:"🧬", params:{model:"text-embedding-3-small"} },
    { id:"5", type:"vectorStore", pos:{x:780, y:320}, label:"Vector Store",  desc:"Pinecone similarity index",       color:"#10b981", icon:"🗄️", params:{provider:"pinecone", topK:"5"} },
    { id:"6", type:"retriever",   pos:{x:540, y:320}, label:"Retriever",     desc:"Find relevant chunks",            color:"#f97316", icon:"🎯", params:{scoreThreshold:"0.7"} },
    { id:"7", type:"llm",         pos:{x:300, y:320}, label:"GPT-4o",        desc:"Generate grounded answer",        color:"#ec4899", icon:"🧠", params:{model:"gpt-4o", temperature:"0.2"} },
    { id:"8", type:"chatUI",      pos:{x:60,  y:320}, label:"Chat UI",       desc:"Conversational interface",        color:"#6366f1", icon:"💬", params:{theme:"dark", stream:"true"} },
  ],
  edges: [
    {id:"e1",src:"1",tgt:"2"},{id:"e2",src:"2",tgt:"3"},{id:"e3",src:"3",tgt:"4"},
    {id:"e4",src:"4",tgt:"5"},{id:"e5",src:"5",tgt:"6"},{id:"e6",src:"6",tgt:"7"},
    {id:"e7",src:"7",tgt:"8"},
  ],
};

const NODE_W = 190;
const NODE_H_BASE = 82;

// ─── Syntax Highlighter ─────────────────────────────────────────────────────────

function tokenize(code, lang) {
  if (lang === "json") {
    return code
      .replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")
      .replace(/("(?:[^"\\]|\\.)*")(\s*:)/g,'<span style="color:#9cdcfe">$1</span>$2')
      .replace(/:\s*("(?:[^"\\]|\\.)*")/g,': <span style="color:#ce9178">$1</span>')
      .replace(/\b(true|false|null)\b/g,'<span style="color:#569cd6">$1</span>')
      .replace(/\b(-?\d+\.?\d*)\b/g,'<span style="color:#b5cea8">$1</span>');
  }
  if (lang === "dockerfile") {
    return code
      .replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")
      .replace(/^(FROM|RUN|COPY|WORKDIR|EXPOSE|CMD|ENV|ARG)(\s)/gm,'<span style="color:#569cd6">$1</span>$2')
      .replace(/#.*/g,'<span style="color:#6a9955">$&</span>');
  }
  return code
    .replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")
    .replace(/(\/\/[^\n]*)/g,'<span style="color:#6a9955">$1</span>')
    .replace(/(`(?:[^`\\]|\\.)*`)/g,'<span style="color:#ce9178">$1</span>')
    .replace(/("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/g,'<span style="color:#ce9178">$1</span>')
    .replace(/\b(import|export|from|const|let|var|function|async|await|return|if|else|for|of|in|new|class|try|catch|throw|default)\b/g,'<span style="color:#c586c0">$1</span>')
    .replace(/\b(true|false|null|undefined)\b/g,'<span style="color:#569cd6">$1</span>')
    .replace(/\b(\d+\.?\d*)\b/g,'<span style="color:#b5cea8">$1</span>');
}

// ─── Code Generator ─────────────────────────────────────────────────────────────

function generateServerCode(workflow) {
  const nodeList = (workflow.nodes||[]).map(n=>`//   ${n.label}: ${n.desc||""}`).join("\n");
  return `/**
 * ${workflow.name} — Generated by RAG Builder
 *
 * Workflow:
${nodeList}
 */
import express from "express";
import cors from "cors";
import multer from "multer";
import pdf from "pdf-parse";
import { OpenAI } from "openai";
import { Pinecone } from "@pinecone-database/pinecone";
import { RecursiveCharacterTextSplitter } from "langchain/text_splitter";

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static("public"));

const openai   = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const pinecone = new Pinecone({ apiKey: process.env.PINECONE_API_KEY });
const INDEX    = "rag-index";

async function getIndex() {
  const list = await pinecone.listIndexes();
  if (!list.indexes?.find(i => i.name === INDEX)) {
    await pinecone.createIndex({
      name: INDEX, dimension: 1536, metric: "cosine",
      spec: { serverless: { cloud: "aws", region: "us-east-1" } },
    });
    await new Promise(r => setTimeout(r, 8000));
  }
  return pinecone.index(INDEX);
}

let idx;
getIndex().then(i => { idx = i; console.log("✓ Pinecone ready"); });

const upload = multer({ storage: multer.memoryStorage() });
app.post("/upload", upload.single("file"), async (req, res) => {
  const { text } = await pdf(req.file.buffer);
  const splitter = new RecursiveCharacterTextSplitter({ chunkSize: 1000, chunkOverlap: 200 });
  const chunks = await splitter.splitText(text);
  const { data } = await openai.embeddings.create({ model: "text-embedding-3-small", input: chunks });
  await idx.upsert(data.map((e, i) => ({
    id: \`c-\${Date.now()}-\${i}\`,
    values: e.embedding,
    metadata: { text: chunks[i], src: req.file.originalname },
  })));
  res.json({ ok: true, chunks: chunks.length });
});

const sessions = {};
app.post("/chat", async (req, res) => {
  const { question, sid = "default" } = req.body;
  if (!sessions[sid]) sessions[sid] = [];
  const qEmbed = await openai.embeddings.create({ model: "text-embedding-3-small", input: question });
  const hits = await idx.query({ vector: qEmbed.data[0].embedding, topK: 5, includeMetadata: true });
  const context = hits.matches.filter(m => m.score > 0.5).map(m => m.metadata.text).join("\\n\\n");
  res.setHeader("Content-Type", "text/event-stream");
  const stream = await openai.chat.completions.create({
    model: "gpt-4o", stream: true, temperature: 0.2,
    messages: [
      { role: "system", content: \`Answer from context only.\\n\\nCONTEXT:\\n\${context}\` },
      ...sessions[sid].slice(-6),
      { role: "user", content: question },
    ],
  });
  let answer = "";
  for await (const c of stream) {
    const d = c.choices[0]?.delta?.content || "";
    if (d) { answer += d; res.write(\`data: \${JSON.stringify({d})}\\n\\n\`); }
  }
  res.write("data: [DONE]\\n\\n"); res.end();
  sessions[sid].push({ role:"user", content:question });
  sessions[sid].push({ role:"assistant", content:answer });
});

app.get("/health", (_, res) => res.json({ ok: true }));
app.listen(3001, () => console.log("🚀 http://localhost:3001"));
`;
}

function generatePackageJson(workflow) {
  return JSON.stringify({
    name: (workflow.name||"rag-app").toLowerCase().replace(/\s+/g,"-"),
    version: "1.0.0", type: "module",
    scripts: { start: "node server.js", dev: "node --watch server.js" },
    dependencies: {
      express: "^4.18.2", cors: "^2.8.5", multer: "^1.4.5-lts.1",
      "pdf-parse": "^1.1.1", openai: "^4.47.0",
      "@pinecone-database/pinecone": "^2.2.2", langchain: "^0.2.5"
    }
  }, null, 2);
}

function generateDockerfile() {
  return `FROM node:20-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN mkdir -p public
EXPOSE 3001
CMD ["node", "server.js"]`;
}

// ─── Edge Layer ─────────────────────────────────────────────────────────────────

function EdgeLayer({ nodes, edges, connecting, mousePos }) {
  const nodeMap = useMemo(() => Object.fromEntries(nodes.map(n=>[n.id,n])), [nodes]);
  const makePath = (x1,y1,x2,y2) => { const cx=(x1+x2)/2; return `M${x1},${y1} C${cx},${y1} ${cx},${y2} ${x2},${y2}`; };
  return (
    <svg style={{ position:"absolute", inset:0, width:"100%", height:"100%", pointerEvents:"none", overflow:"visible" }}>
      <defs>
        <marker id="arr" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto">
          <path d="M0,0 L0,6 L8,3 z" fill="#4b5563" />
        </marker>
        <marker id="arr-live" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto">
          <path d="M0,0 L0,6 L8,3 z" fill="#6366f1" />
        </marker>
      </defs>
      {edges.map(e => {
        const s=nodeMap[e.src], t=nodeMap[e.tgt]; if(!s||!t) return null;
        const x1=s.pos.x+NODE_W, y1=s.pos.y+NODE_H_BASE/2, x2=t.pos.x, y2=t.pos.y+NODE_H_BASE/2;
        return <path key={e.id} d={makePath(x1,y1,x2,y2)} stroke="#2d2d4a" strokeWidth="2" fill="none" markerEnd="url(#arr)" style={{strokeDasharray:"6 3",animation:"dash 1.5s linear infinite"}} />;
      })}
      {connecting && mousePos && (() => {
        const s=nodeMap[connecting]; if(!s) return null;
        const x1=s.pos.x+NODE_W, y1=s.pos.y+NODE_H_BASE/2;
        return <path d={makePath(x1,y1,mousePos.x,mousePos.y)} stroke="#6366f1" strokeWidth="2" fill="none" strokeDasharray="5 3" markerEnd="url(#arr-live)" />;
      })()}
    </svg>
  );
}

// ─── Node Card ──────────────────────────────────────────────────────────────────

function NodeCard({ node, selected, onMouseDown, onDelete, onParamChange, onStartConnect, onEndConnect }) {
  const [expanded, setExpanded] = useState(false);
  const show = expanded || selected;
  return (
    <div onMouseDown={onMouseDown} style={{
      position:"absolute", left:node.pos.x, top:node.pos.y, width:NODE_W,
      background:"#0c0c18", border:`1.5px solid ${selected?node.color:"#1e1e30"}`,
      borderRadius:12, boxShadow:selected?`0 0 0 3px ${node.color}28,0 8px 32px #00000090`:"0 4px 20px #00000070",
      cursor:"grab", userSelect:"none", transition:"border-color .15s,box-shadow .15s",
      zIndex:selected?20:1, overflow:"hidden",
    }}>
      <div style={{ height:3, background:`linear-gradient(90deg,${node.color}00,${node.color},${node.color}00)` }} />
      <div style={{ padding:"10px 12px" }}>
        <div style={{ display:"flex", alignItems:"center", gap:8, marginBottom:5 }}>
          <div style={{ width:28,height:28,borderRadius:7,flexShrink:0,background:`${node.color}18`,border:`1px solid ${node.color}40`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13 }}>{node.icon}</div>
          <span style={{ fontWeight:700,fontSize:12.5,color:"#e2e2ef",flex:1,letterSpacing:-.2 }}>{node.label}</span>
          <button onMouseDown={e=>e.stopPropagation()} onClick={()=>setExpanded(v=>!v)} style={{ background:"none",border:"none",color:"#444",cursor:"pointer",fontSize:12,padding:2 }}>{show?"▲":"▼"}</button>
        </div>
        <p style={{ fontSize:10.5,color:"#4a4a6a",margin:0,lineHeight:1.5 }}>{node.desc}</p>
        {show && node.params && (
          <div style={{ marginTop:10,paddingTop:9,borderTop:`1px solid ${node.color}22` }}>
            {Object.entries(node.params).map(([k,v])=>(
              <div key={k} style={{ display:"flex",alignItems:"center",gap:5,marginBottom:4 }}>
                <span style={{ fontSize:9.5,color:"#3a3a58",flex:"0 0 68px",fontFamily:"monospace" }}>{k}</span>
                <input defaultValue={String(v)} onMouseDown={e=>e.stopPropagation()} onChange={e=>onParamChange(node.id,k,e.target.value)}
                  style={{ flex:1,background:`${node.color}0d`,border:`1px solid ${node.color}28`,borderRadius:4,padding:"2px 6px",color:node.color,fontSize:10,fontFamily:"monospace",outline:"none" }} />
              </div>
            ))}
            <button onMouseDown={e=>e.stopPropagation()} onClick={()=>onDelete(node.id)} style={{ marginTop:6,width:"100%",background:"#3f0f0f44",border:"1px solid #7f1d1d88",borderRadius:5,color:"#f87171",fontSize:10,padding:"3px 0",cursor:"pointer" }}>Remove node</button>
          </div>
        )}
      </div>
      <div onMouseDown={e=>{e.stopPropagation();onStartConnect(node.id);}} title="Drag to connect"
        style={{ position:"absolute",right:-6,top:"50%",transform:"translateY(-50%)",width:12,height:12,borderRadius:"50%",background:node.color,border:"2px solid #0c0c18",cursor:"crosshair",zIndex:10 }} />
      <div onMouseUp={e=>{e.stopPropagation();onEndConnect(node.id);}}
        style={{ position:"absolute",left:-6,top:"50%",transform:"translateY(-50%)",width:12,height:12,borderRadius:"50%",background:"#2a2a42",border:"2px solid #0c0c18",cursor:"crosshair",zIndex:10 }} />
    </div>
  );
}

// ─── Node Editor ────────────────────────────────────────────────────────────────

function NodeEditor({ workflow }) {
  const [nodes, setNodes] = useState(workflow.nodes);
  const [edges, setEdges] = useState(workflow.edges);
  const [selected, setSelected] = useState(null);
  const [connecting, setConnecting] = useState(null);
  const [mousePos, setMousePos] = useState(null);
  const [pan, setPan] = useState({ x:0, y:0 });
  const [panStart, setPanStart] = useState(null);
  const canvasRef = useRef(null);
  const draggingNode = useRef(null);

  useEffect(() => { setNodes(workflow.nodes); setEdges(workflow.edges); }, [workflow]);

  const handleCanvasMouseDown = (e) => {
    if (e.target === canvasRef.current || e.target.tagName === "svg" || e.target.tagName === "SVG") {
      setSelected(null);
      setPanStart({ x:e.clientX-pan.x, y:e.clientY-pan.y });
    }
  };

  const handleMouseMove = useCallback((e) => {
    const rect = canvasRef.current?.getBoundingClientRect(); if(!rect) return;
    setMousePos({ x:e.clientX-rect.left-pan.x, y:e.clientY-rect.top-pan.y });
    if (draggingNode.current) {
      const {id,ox,oy} = draggingNode.current;
      setNodes(ns=>ns.map(n=>n.id===id?{...n,pos:{x:e.clientX-ox-rect.left,y:e.clientY-oy-rect.top}}:n));
    } else if (panStart) {
      setPan({ x:e.clientX-panStart.x, y:e.clientY-panStart.y });
    }
  }, [pan, panStart]);

  const handleMouseUp = () => { draggingNode.current=null; setPanStart(null); if(connecting) setConnecting(null); };

  const startDragNode = (node,e) => {
    e.stopPropagation(); setSelected(node.id);
    const rect = canvasRef.current.getBoundingClientRect();
    draggingNode.current = { id:node.id, ox:e.clientX-node.pos.x-rect.left, oy:e.clientY-node.pos.y-rect.top };
  };

  const deleteNode = (id) => { setNodes(ns=>ns.filter(n=>n.id!==id)); setEdges(es=>es.filter(e=>e.src!==id&&e.tgt!==id)); setSelected(null); };
  const paramChange = (id,k,v) => setNodes(ns=>ns.map(n=>n.id===id?{...n,params:{...n.params,[k]:v}}:n));
  const endConnect = (tgtId) => {
    if(connecting&&connecting!==tgtId&&!edges.find(e=>e.src===connecting&&e.tgt===tgtId))
      setEdges(es=>[...es,{id:`e${Date.now()}`,src:connecting,tgt:tgtId}]);
    setConnecting(null);
  };

  const addNode = () => {
    const types=Object.keys(NODE_DEFS), type=types[Math.floor(Math.random()*types.length)], def=NODE_DEFS[type];
    setNodes(ns=>[...ns,{ id:String(Date.now()),type,pos:{x:120+Math.random()*400,y:80+Math.random()*300},label:type,desc:"New node",color:def.color,icon:def.icon,params:{param:"value"} }]);
  };

  return (
    <div style={{ flex:1,display:"flex",flexDirection:"column",minHeight:0 }}>
      <div style={{ display:"flex",alignItems:"center",gap:8,padding:"7px 14px",borderBottom:"1px solid #12122a",background:"#07070e",flexShrink:0 }}>
        <span style={{ fontSize:11,color:"#333",fontFamily:"monospace" }}>{nodes.length} nodes · {edges.length} edges</span>
        <div style={{ flex:1 }} />
        <span style={{ fontSize:10,color:"#252538" }}>drag handle to connect • click node to edit • drag canvas to pan</span>
        <button onClick={addNode} style={{ background:"#1a1a2e",border:"1px solid #2a2a42",color:"#6366f1",borderRadius:6,padding:"4px 12px",cursor:"pointer",fontSize:11,fontFamily:"monospace" }}>+ Add Node</button>
      </div>
      <div ref={canvasRef} onMouseDown={handleCanvasMouseDown} onMouseMove={handleMouseMove} onMouseUp={handleMouseUp} onMouseLeave={handleMouseUp}
        style={{ flex:1,position:"relative",overflow:"hidden",background:"#07070e",cursor:panStart?"grabbing":"default" }}>
        <svg style={{ position:"absolute",inset:0,width:"100%",height:"100%",pointerEvents:"none" }}>
          <defs><pattern id="dots" width="30" height="30" patternUnits="userSpaceOnUse" patternTransform={`translate(${pan.x%30},${pan.y%30})`}><circle cx="15" cy="15" r="1" fill="#14142a"/></pattern></defs>
          <rect width="100%" height="100%" fill="url(#dots)"/>
        </svg>
        <style>{`@keyframes dash{to{stroke-dashoffset:-18}}`}</style>
        <div style={{ position:"absolute",left:pan.x,top:pan.y,width:0,height:0 }}>
          <div style={{ position:"relative" }}>
            <EdgeLayer nodes={nodes} edges={edges} connecting={connecting} mousePos={mousePos}/>
            {nodes.map(node=>(
              <NodeCard key={node.id} node={node} selected={selected===node.id}
                onMouseDown={e=>startDragNode(node,e)} onDelete={deleteNode}
                onParamChange={paramChange} onStartConnect={setConnecting} onEndConnect={endConnect}/>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Code Viewer ────────────────────────────────────────────────────────────────

function CodeViewer({ workflow }) {
  const files = useMemo(()=>[
    { key:"server",  label:"server.js",     lang:"javascript", content:generateServerCode(workflow) },
    { key:"pkg",     label:"package.json",  lang:"json",       content:generatePackageJson(workflow) },
    { key:"docker",  label:"Dockerfile",    lang:"dockerfile", content:generateDockerfile() },
    { key:"env",     label:".env.example",  lang:"plaintext",  content:"OPENAI_API_KEY=sk-...\nPINECONE_API_KEY=pcsk-..." },
  ],[workflow]);
  const [activeKey,setActiveKey]=useState("server");
  const [copied,setCopied]=useState(false);
  const current=files.find(f=>f.key===activeKey);
  const copy=()=>{ navigator.clipboard?.writeText(current.content); setCopied(true); setTimeout(()=>setCopied(false),1500); };
  const downloadAll=()=>files.forEach(f=>{ const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([f.content],{type:"text/plain"})); a.download=f.label; a.click(); });
  const lines=current.content.split("\n");
  return (
    <div style={{ flex:1,display:"flex",flexDirection:"column",minHeight:0 }}>
      <div style={{ display:"flex",alignItems:"center",borderBottom:"1px solid #12122a",background:"#07070e",padding:"0 14px",flexShrink:0 }}>
        {files.map(f=>(
          <button key={f.key} onClick={()=>setActiveKey(f.key)} style={{ background:"none",border:"none",borderBottom:activeKey===f.key?"2px solid #6366f1":"2px solid transparent",color:activeKey===f.key?"#a0a0ff":"#3a3a58",padding:"9px 14px",cursor:"pointer",fontSize:12,fontFamily:"monospace",marginBottom:-1,transition:"color .15s" }}>{f.label}</button>
        ))}
        <div style={{ flex:1 }}/>
        <button onClick={copy} style={{ background:"#12121e",border:"1px solid #1e1e30",color:copied?"#4ade80":"#555",borderRadius:6,padding:"4px 10px",cursor:"pointer",fontSize:11,fontFamily:"monospace",marginRight:6 }}>{copied?"✓ copied":"copy"}</button>
        <button onClick={downloadAll} style={{ background:"#1a1a30",border:"1px solid #4f46e5",color:"#8080ff",borderRadius:6,padding:"4px 10px",cursor:"pointer",fontSize:11,fontFamily:"monospace" }}>⬇ all</button>
      </div>
      <div style={{ flex:1,overflow:"auto",background:"#070710",padding:"14px 0" }}>
        <table style={{ borderCollapse:"collapse",width:"100%",fontFamily:"monospace",fontSize:12.5 }}>
          <tbody>
            {lines.map((line,i)=>(
              <tr key={i} style={{ lineHeight:1.65 }}>
                <td style={{ width:46,textAlign:"right",padding:"0 16px 0 8px",color:"#252540",userSelect:"none",borderRight:"1px solid #12122a",verticalAlign:"top",fontVariantNumeric:"tabular-nums" }}>{i+1}</td>
                <td style={{ padding:"0 16px",color:"#c8c8d8",whiteSpace:"pre" }} dangerouslySetInnerHTML={{ __html:tokenize(line,current.lang) }}/>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ─── Embed Panel ─────────────────────────────────────────────────────────────────

function EmbedPanel({ result }) {
  const [copied,setCopied]=useState(false);
  const embedCode=`<iframe\n  src="http://localhost:3001"\n  width="100%"\n  height="650"\n  frameborder="0"\n  title="${result.workflow?.name||"RAG App"}"\n></iframe>`;
  return (
    <div style={{ padding:24,overflowY:"auto",display:"flex",flexDirection:"column",gap:20 }}>
      <div style={{ background:"#091409",border:"1px solid #14532d44",borderRadius:12,padding:20,display:"flex",gap:14 }}>
        <div style={{ width:42,height:42,borderRadius:10,background:"#14532d33",border:"1px solid #14532d",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,flexShrink:0 }}>✓</div>
        <div>
          <div style={{ fontWeight:800,fontSize:15,color:"#4ade80",marginBottom:4 }}>{result.workflow?.name} — ready</div>
          <div style={{ fontSize:11,color:"#333",fontFamily:"monospace" }}>
            {result.workflow?.nodes?.length} nodes · {result.workflow?.edges?.length} edges
            {result.aiUsed&&<span style={{ color:"#4ade80",marginLeft:10 }}>● AI-generated</span>}
          </div>
        </div>
      </div>
      <div>
        <div style={{ fontSize:10,color:"#333",fontFamily:"monospace",letterSpacing:1,textTransform:"uppercase",marginBottom:8 }}>Embed Code</div>
        <div style={{ position:"relative" }}>
          <pre style={{ background:"#09090f",border:"1px solid #1a1a2a",borderRadius:10,padding:"14px 16px",fontSize:12.5,color:"#8080aa",fontFamily:"monospace",whiteSpace:"pre-wrap",margin:0,lineHeight:1.7 }}>{embedCode}</pre>
          <button onClick={()=>{ navigator.clipboard?.writeText(embedCode); setCopied(true); setTimeout(()=>setCopied(false),1500); }}
            style={{ position:"absolute",top:8,right:8,background:"#12121e",border:"1px solid #1e1e30",color:copied?"#4ade80":"#555",borderRadius:5,padding:"3px 8px",cursor:"pointer",fontSize:10,fontFamily:"monospace" }}>{copied?"✓":"copy"}</button>
        </div>
      </div>
      <div style={{ background:"#0c0c18",border:"1px solid #1a1a2a",borderRadius:12,padding:18 }}>
        <div style={{ fontWeight:700,fontSize:12,color:"#555",marginBottom:12 }}>🚀 Steps to deploy</div>
        {["Download all files (Code tab → ⬇ all)","cp .env.example .env  and add your API keys","npm install && npm start","Paste the embed code into your website"].map((s,i)=>(
          <div key={i} style={{ display:"flex",gap:10,marginBottom:10,alignItems:"flex-start" }}>
            <div style={{ width:20,height:20,borderRadius:5,background:"#1a1a30",border:"1px solid #4f46e5",color:"#6366f1",fontSize:10,fontFamily:"monospace",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,flexShrink:0 }}>{i+1}</div>
            <code style={{ fontSize:12,color:"#4a4a6a",lineHeight:1.6 }}>{s}</code>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── AI Call ──────────────────────────────────────────────────────────────────

async function callAI(prompt, apiKey) {
  const sys = `You are a RAG app architect. Given a description, return ONLY a JSON object (no markdown) with:
- name: string
- nodes: array of {id,type,pos:{x,y},label,desc,color,icon,params:{key:val}}
  id: sequential "1","2",...
  type: one of fileInput|processor|embeddings|vectorStore|retriever|llm|chatUI|output|webScraper|apiInput
  pos: x from 60 to 900 step ~240, y alternates 120 and 320
  color: hex from #3b82f6 #8b5cf6 #f59e0b #10b981 #f97316 #ec4899 #6366f1 #14b8a6 #a855f7 #06b6d4
  icon: relevant emoji
  params: 2-4 config params as key:"value"
- edges: array of {id,src,tgt}`;
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method:"POST",
    headers:{ "Content-Type":"application/json", "x-api-key": apiKey, "anthropic-version":"2023-06-01", "anthropic-dangerous-direct-browser-access":"true" },
    body:JSON.stringify({ model:"claude-sonnet-4-20250514", max_tokens:1800, system:sys, messages:[{role:"user",content:`RAG app: ${prompt}`}] }),
  });
  const data = await res.json();
  const raw = data.content?.[0]?.text||"";
  return JSON.parse(raw.replace(/^```(?:json)?\n?/,"").replace(/\n?```$/,"").trim());
}

// ─── Main App ─────────────────────────────────────────────────────────────────

export default function App() {
  const [prompt,setPrompt]=useState("");
  const [loading,setLoading]=useState(false);
  const [result,setResult]=useState(null);
  const [error,setError]=useState(null);
  const [activeTab,setActiveTab]=useState("editor");
  const [showKeys,setShowKeys]=useState(false);
  const [apiKey,setApiKey]=useState("");

  const examples=["PDF Q&A chatbot","YouTube transcript bot","Legal doc analyzer","Customer support RAG","Research assistant"];

  const generate=async()=>{
    if(!prompt.trim()||loading) return;
    setLoading(true); setError(null); setResult(null);
    try {
      let workflow, aiUsed=false;
      if(apiKey.trim()){
        try { workflow=await callAI(prompt,apiKey); aiUsed=true; }
        catch(e){ console.warn("AI failed:",e.message); workflow=DEFAULT_WORKFLOW; }
      } else {
        await new Promise(r=>setTimeout(r,800));
        workflow=DEFAULT_WORKFLOW;
      }
      setResult({workflow,aiUsed}); setActiveTab("editor");
    } catch(e){ setError(e.message); }
    finally{ setLoading(false); }
  };

  const TABS=[{id:"editor",label:"⬡  Node Editor"},{id:"code",label:"</> Code"},{id:"embed",label:"{}  Embed"}];

  return (
    <div style={{ height:"100vh",display:"flex",flexDirection:"column",background:"#06060f",color:"#e0e0f0",fontFamily:"'Segoe UI',system-ui,sans-serif" }}>
      <style>{`@keyframes spin{to{transform:rotate(360deg)}} @keyframes fadeUp{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}} @keyframes pulse{0%,100%{opacity:.4}50%{opacity:.8}} *{box-sizing:border-box} ::-webkit-scrollbar{width:5px;height:5px} ::-webkit-scrollbar-track{background:transparent} ::-webkit-scrollbar-thumb{background:#1e1e30;border-radius:3px} input,button{font-family:inherit}`}</style>

      {/* Header */}
      <header style={{ height:50,display:"flex",alignItems:"center",padding:"0 20px",gap:12,borderBottom:"1px solid #10102a",background:"#04040c",flexShrink:0 }}>
        <svg width="24" height="24" viewBox="0 0 24 24"><rect width="24" height="24" rx="6" fill="url(#hg)"/><polygon points="12,4 20,20 4,20" fill="none" stroke="white" strokeWidth="1.5" strokeLinejoin="round"/><defs><linearGradient id="hg" x1="0" y1="0" x2="24" y2="24"><stop stopColor="#4f46e5"/><stop offset="1" stopColor="#7c3aed"/></linearGradient></defs></svg>
        <span style={{ fontWeight:800,fontSize:16,letterSpacing:-.4 }}>RAG Builder</span>
        <span style={{ fontSize:9,padding:"2px 6px",borderRadius:4,background:"#1a1830",border:"1px solid #4f46e5",color:"#6366f1",fontFamily:"monospace",letterSpacing:.5 }}>MVP</span>
        <div style={{ flex:1 }}/>
        <button onClick={()=>setShowKeys(v=>!v)} style={{ background:"transparent",border:"1px solid #1e1e30",color:apiKey?"#6366f1":"#333",borderRadius:7,padding:"5px 12px",cursor:"pointer",fontSize:12 }}>🔑 {apiKey?"Key set ✓":"Add API Key"}</button>
      </header>

      {/* Prompt */}
      <div style={{ padding:"16px 20px 12px",borderBottom:"1px solid #10102a",background:"#04040c",flexShrink:0 }}>
        {showKeys&&(
          <div style={{ marginBottom:10,animation:"fadeUp .2s ease" }}>
            <label style={{ fontSize:10,color:"#333",fontFamily:"monospace",display:"block",marginBottom:4 }}>ANTHROPIC API KEY (optional — enables AI workflow generation)</label>
            <input type="password" placeholder="sk-ant-..." value={apiKey} onChange={e=>setApiKey(e.target.value)}
              style={{ width:320,background:"#0c0c1a",border:"1px solid #1e1e30",borderRadius:7,padding:"7px 10px",color:"#a0a0cc",fontSize:12,fontFamily:"monospace",outline:"none" }}/>
          </div>
        )}
        <div style={{ display:"flex",gap:8,marginBottom:8 }}>
          <input value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>e.key==="Enter"&&generate()}
            placeholder="Describe your RAG app… e.g. PDF Q&A chatbot for support docs"
            style={{ flex:1,background:"#0c0c1a",border:"1.5px solid #1e1e30",borderRadius:9,padding:"12px 15px",color:"#e0e0f0",fontSize:14,outline:"none",transition:"border-color .2s" }}
            onFocus={e=>e.target.style.borderColor="#4f46e5"} onBlur={e=>e.target.style.borderColor="#1e1e30"}/>
          <button onClick={generate} disabled={loading||!prompt.trim()}
            style={{ background:loading?"#14142a":"linear-gradient(135deg,#4f46e5,#7c3aed)",color:loading?"#333":"#fff",border:"none",borderRadius:9,padding:"12px 24px",cursor:loading?"wait":"pointer",fontWeight:800,fontSize:14,letterSpacing:-.3,whiteSpace:"nowrap",opacity:!prompt.trim()?0.4:1,transition:"opacity .15s" }}>
            {loading?<span style={{display:"flex",alignItems:"center",gap:7}}><span style={{width:12,height:12,border:"2px solid #333",borderTopColor:"#6366f1",borderRadius:"50%",display:"inline-block",animation:"spin .6s linear infinite"}}/>Working…</span>:"Generate →"}
          </button>
        </div>
        <div style={{ display:"flex",gap:5,flexWrap:"wrap" }}>
          {examples.map(ex=>(
            <button key={ex} onClick={()=>setPrompt(ex)} style={{ background:"#0c0c1a",border:"1px solid #1a1a2a",color:"#333",borderRadius:14,padding:"3px 11px",cursor:"pointer",fontSize:11,transition:"all .15s" }}
              onMouseOver={e=>{e.currentTarget.style.color="#8080ff";e.currentTarget.style.borderColor="#4f46e5";}}
              onMouseOut={e=>{e.currentTarget.style.color="#333";e.currentTarget.style.borderColor="#1a1a2a";}}>{ex}</button>
          ))}
        </div>
      </div>

      {error&&<div style={{ margin:"10px 20px 0",background:"#1a0505",border:"1px solid #7f1d1d55",borderRadius:8,padding:"8px 14px",color:"#f87171",fontSize:12,fontFamily:"monospace",flexShrink:0 }}>⚠ {error}</div>}

      {/* Empty state */}
      {!result&&!loading&&(
        <div style={{ flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:14,color:"#1e1e30" }}>
          <svg width="90" height="70" viewBox="0 0 90 70" fill="none">
            {[[10,25],[36,5],[62,25],[36,45]].map(([x,y],i)=>(
              <rect key={i} x={x} y={y} width="22" height="18" rx="4" stroke={["#4f46e5","#06b6d4","#10b981","#ec4899"][i]} strokeWidth="1.2" fill="none"/>
            ))}
            <line x1="32" y1="34" x2="36" y2="34" stroke="#4f46e5" strokeWidth="1" strokeDasharray="2 2"/>
            <line x1="58" y1="34" x2="62" y2="34" stroke="#4f46e5" strokeWidth="1" strokeDasharray="2 2"/>
            <line x1="47" y1="23" x2="47" y2="45" stroke="#4f46e5" strokeWidth="1" strokeDasharray="2 2"/>
          </svg>
          <p style={{ fontSize:13,fontFamily:"monospace" }}>type a prompt above to generate a workflow</p>
        </div>
      )}

      {/* Loading */}
      {loading&&(
        <div style={{ flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:14 }}>
          <div style={{ width:44,height:44,borderRadius:"50%",border:"3px solid #12122a",borderTopColor:"#6366f1",animation:"spin .7s linear infinite" }}/>
          <div style={{ fontSize:13,color:"#333",fontFamily:"monospace" }}>{apiKey?"Calling Claude to design your workflow…":"Building workflow from template…"}</div>
          <div style={{ fontSize:11,color:"#1e1e30",fontFamily:"monospace",animation:"pulse 1.5s ease infinite" }}>Generating nodes · Writing server code · Creating embed</div>
        </div>
      )}

      {/* Workspace */}
      {result&&!loading&&(
        <div style={{ flex:1,display:"flex",flexDirection:"column",minHeight:0,animation:"fadeUp .3s ease" }}>
          <div style={{ display:"flex",borderBottom:"1px solid #10102a",background:"#04040c",padding:"0 14px",flexShrink:0 }}>
            {TABS.map(t=>(
              <button key={t.id} onClick={()=>setActiveTab(t.id)} style={{ background:"none",border:"none",borderBottom:activeTab===t.id?"2px solid #6366f1":"2px solid transparent",color:activeTab===t.id?"#a0a0ff":"#333",padding:"9px 16px",cursor:"pointer",fontSize:12,fontFamily:"monospace",marginBottom:-1,transition:"color .15s" }}>{t.label}</button>
            ))}
            <div style={{ flex:1 }}/>
            <span style={{ alignSelf:"center",fontSize:10,color:"#1e1e30",fontFamily:"monospace",marginRight:4 }}>
              {result.workflow?.name}{result.aiUsed&&<span style={{color:"#4ade80",marginLeft:8}}>● AI</span>}
            </span>
          </div>
          <div style={{ flex:1,minHeight:0,display:"flex",flexDirection:"column" }}>
            {activeTab==="editor"&&<NodeEditor workflow={result.workflow} key={result.workflow.name}/>}
            {activeTab==="code"&&<CodeViewer workflow={result.workflow}/>}
            {activeTab==="embed"&&<EmbedPanel result={result}/>}
          </div>
        </div>
      )}
    </div>
  );
}
